baseURL = "http://cacti02-1549.cloud.plgrid.pl/nz61www/public/"
#baseURL = "/"
languageCode = "en-us"
DefaultContentLanguage = "en"

title = "Docdock"
theme = "docdock"
#themesdir = "../.."

[params]
editURL = "https://github.com/vjeantet/hugo-theme-docdock/edit/master/exampleSite/content/"
showVisitedLinks = true # default is false
themeStyle = "original" # "original" or "flex" # default "original"
themeVariant = "" # choose theme variant "green", "gold" , "gray", "blue" (default)
ordersectionsby = "weight" # ordersectionsby = "title"
disableHomeIcon = false # default is false
disableSearch = false # default is false
disableNavChevron = true # set true to hide next/prev chevron, default is false

[outputs]
home = [ "HTML", "RSS", "JSON"]


[[menu.shortcuts]]
pre = "<h3>More</h3>"
name = "<i class='fa fa-github'></i> Github repo"
identifier = "ds"
url = "https://github.com/vjeantet/hugo-theme-docdock"
weight = 10

